server:
  port: 9778
  servlet:
    session:
      timeout: 30d
      cookie:
        name: PVSESSION
        http-only: true
        max-age: 30d   # <- persistente (no se borra al cerrar el navegador)
        secure: false  # true si vas detrás de HTTPS
        same-site: lax

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
        provider:
          google:
            issuer-uri: https://accounts.google.com

app:
  base-url: ${APP_BASE_URL:http://localhost:9778}